when@dev:
    web_profiler:
        toolbar: true

    framework:
        profiler:
            collect_serializer_data: true

when@test:
    framework:
        profiler:
            # Pour collecter les données dans le profiler de dev (si besoin de debug)
            # Note: activer le mode debug APP_DEBUG=true dans phpunit.xml
            enabled: true
            collect: true
            only_exceptions: false
            dsn: 'file:%kernel.project_dir%/var/cache/dev/profiler'
