api_login_check:
    path: /auth
    methods: [POST]

api_refresh_token:
    path: /auth/refresh

api_token_invalidate:
    path: /auth/logout

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
