api_refresh_token:
    path: /auth/refresh

api_token_invalidate:
    path: /auth/logout

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Routes générées par le bundle WebAuthn (recette Flex non appliquée : allow-contrib est à false)
webauthn:
    resource: .
    type: webauthn
